fineract:
  enabled: true
  db: cloud-sql-proxy
  DFSPIDS: ""
  SPRING_PROFILES_ACTIVE: "test"
  image: ""
  spec: 
    template:
      spec:
        containers:
          env:
            FINERACT_DEFAULT_TENANTDB_IDENTIFIER: ""
            FINERACT_DEFAULT_TENANTDB_NAME: ""
            FINERACT_DEFAULT_TENANTDB_HOSTNAME: 127.0.0.1
            FINERACT_DEFAULT_TENANTDB_PORT: 3306
            FINERACT_HIKARI_PASSWORD: ""
            FINERACT_DEFAULT_TENANTDB_PWD: ""
            FINERACT_HIKARI_USERNAME: ""
            FINERACT_ADMIN_USERNAME: ""
            FINERACT_HIKARI_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
            FINERACT_HIKARI_JDBC_URL: "jdbc:mysql://127.0.0.1:3306/fineract_tenants?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sessionVariables=time_zone='-00:00'"
            FINERACT_SERVER_PORT: 8080
            CONTAINER_PORT: 80
  preStopScript: 'echo -e "******Fineract is stopping********";'
  ingress:
    enabled: true
    hostname: "kemetx.kemetstax.org"
    path: "/"
    wildcardhostname: "*.kemetstax.org"
    annotations:
      # This tells Google Cloud to associate the External Load Balancer with the static IP which we created earlier
      kubernetes.io/ingress.global-static-ip-name: kemetstack-static-ip
      networking.gke.io/managed-certificates: kemetstax-managed-cert
      # kubernetes.io/ingress.class: "nginx"
      # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # This tells Google Cloud to create an External Load Balancer to realize this Ingress
      kubernetes.io/ingress.class: "gce"
#      ingressClassName: "nginx"
      # This enables HTTP connections from Internet clients
      kubernetes.io/ingress.allow-http: "false"
  resources:
    limits:
      cpu: "2000m"
      memory: "8Gi"
    requests:
      cpu: "500m"
      memory: "2Gi"
  deployment:
    extraEnvs:
      - name: "FINERACT_SECURITY_BASICAUTH_ENABLED"
        value: 'true'
      - name: "FINERACT_SECURITY_OAUTH_ENABLED"
        value: 'false'

webapp:
  enabled: true
#  lookforservice: true
  image: "almbolonzi/web-app:1.0.0"
  ingress:
    enabled: false
    hostname: "web.kemetstax.org"
    path: "/"
    annotations:
      kubernetes.io/ingress.class: "gce"
#      ingressClassName: "gce"
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "0.5Gi"

selfservice:
  enabled: true
  image: "almbolonzi/web-self-service-app:1.0.0"
  ingress:
    enabled: false
    hostname: "self.kemetstax.org"
    path: "/"
    annotations:
      kubernetes.io/ingress.class: "gce"

# mysql:
#   fullnameOverride: fineract-mysql
#   enabled: false
#   image:
#     tag: "8.2.0-debian-11-r5"
#     debug: true
#   auth:
#     username: "mifos"
#     password: "password"
#     rootPassword: "4ET6ywqlGt"
#   initdbScripts:
#     setup.sql: |-
#       create databases
#       CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
#       CREATE DATABASE IF NOT EXISTS `fineract_default`;
#       create root user and grant rights
#       GRANT ALL ON *.* TO 'root'@'%';
#       GRANT ALL PRIVILEGES ON `fineract_tenants`.* TO 'mifos';
#       GRANT ALL PRIVILEGES ON `fineract_default`.* TO 'mifos';
#   primary:
#     resources:
#       requests:
#         memory: "0.5Gi"
#         cpu: "500m"
#       limits:
#         memory: "1Gi"
#         cpu: "1000m"

# wildcardhostname: "*.kemetstack.org"
# tls: ""
