fineract:
  enabled: true
#  db: fineract-mysql
  DFSPIDS: ""
  SPRING_PROFILES_ACTIVE: "bb"
  image: ""
  spec: 
    template:
       spec:
         containers:
            env:
              FINERACT_DEFAULT_TENANTDB_IDENTIFIER: ${{ secrets.FINERACT_DEFAULT_TENANTDB_IDENTIFIER_TEST }}
              FINERACT_DEFAULT_TENANTDB_NAME: ${{ secrets.FINERACT_DEFAULT_TENANTDB_NAME_TEST }}
              FINERACT_DEFAULT_TENANTDB_HOSTNAME: ${{ secrets.FINERACT_DEFAULT_TENANTDB_HOSTNAME_TEST }}
#              FINERACT_DEFAULT_TENANTDB_PORT: ${{ secrets.FINERACT_DEFAULT_TENANTDB_PORT_TEST }}
              FINERACT_HIKARI_PASSWORD: ${{ secrets.FINERACT_HIKARI_PASSWORD_TEST }}
              FINERACT_HIKARI_USERNAME: ${{ secrets.FINERACT_HIKARI_USERNAME_TEST }}
              FINERACT_HIKARI_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
              FINERACT_HIKARI_JDBC_URL: jdbc:mysql://$FINERACT_DEFAULT_TENANTDB_HOSTNAME?${{ secrets.FINERACT_HIKARI_JDBC_URL_TEST }}&socketFactory=com.google.cloud.sql.mysql.SocketFactory&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=time_zone=`-00:00`
              FINERACT_SERVER_PORT: 8080
              CONTAINER_PORT: 80
  preStopScript: 'echo -e "******Fineract is stopping********";'
  ingress:
    enabled: true
    hostname: "kemetx.kemetstack.org"
    path: "/"
    #wildcardhostname: "*.kemetstack.org"
    annotations:
      #kubernetes.io/ingress.class: "nginx"
      #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" 
      # This tells Google Cloud to create an External Load Balancer to realize this Ingress
      kubernetes.io/ingress.class: gce
      #ingressClassName: "gce"
      # This enables HTTP connections from Internet clients
      kubernetes.io/ingress.allow-http: "false"
      # This tells Google Cloud to associate the External Load Balancer with the static IP which we created earlier
      kubernetes.io/ingress.global-static-ip-name: kemetstack-static-ip
      networking.gke.io/managed-certificates: kemetstack-managed-cert
  resources:
    limits:
      cpu: "2000m"
      memory: "4Gi"
    requests:
      cpu: "1000m"
      memory: "2Gi"
  deployment:
    extraEnvs:
      - name: "FINERACT_SECURITY_BASICAUTH_ENABLED"
        value: 'true'
      - name: "FINERACT_SECURITY_OAUTH_ENABLED"
        value: 'false'

#communityapp:
#  enabled: false
#  lookforservice: true
#  image: "almbolonzi/mifos-community-app:latest"
#  ingress:
#    enabled: false
#    hostname: "communityapp.kemetstack.org"
#    path: "/"
#    wildcardhostname: "*.communityapp.kemetstack.org"
#    annotations:
#      kubernetes.io/ingress.class: "gce"
#  resources:
#    limits:
#      cpu: "500m"
#      memory: "1Gi"
#    requests:
#      cpu: "500m"
#      memory: "0.5Gi"
#
webapp:
  enabled: false
  lookforservice: true
  image: "almbolonzi/web-app:1.0.0"
  ingress:
    enabled: false
    hostname: "web.kemetstack.org"
    path: "/"
    annotations:
      kubernetes.io/ingress.class: gce
      ingressClassName: "gce"
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "0.5Gi"

selfservice:
  enabled: false
  image: "almbolonzi/web-self-service-app:1.0.0"
  ingress:
    enabled: false
    hostname: "self.kemetstack.org"
    path: "/"
    annotations:
      kubernetes.io/ingress.class: gce




#mysql:
#  fullnameOverride: fineract-mysql
#  enabled: false
#  image:
#    tag: "8.2.0-debian-11-r5"
#    debug: true
#  auth:
#    username: "mifos"
#    password: "password"
#    rootPassword: "4ET6ywqlGt"
#  initdbScripts:
#    setup.sql: |-
#       create databases
#      CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
#      CREATE DATABASE IF NOT EXISTS `fineract_default`;
#       create root user and grant rights
#      GRANT ALL ON *.* TO 'root'@'%';
#      GRANT ALL PRIVILEGES ON `fineract_tenants`.* TO 'mifos';
#      GRANT ALL PRIVILEGES ON `fineract_default`.* TO 'mifos';
#  primary:
#    resources:
#      requests:
#        memory: "0.5Gi"
#        cpu: "500m"
#      limits:
#        memory: "1Gi"
#        cpu: "1000m"

#wildcardhostname: "*.kemetstack.org"

#tls: ""  