{{- if .Values.webapp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-service
  labels:
    app: self-service
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: self-service
  template:
    metadata:
      labels:
        app: self-service
        tier: frontend
    spec:
      containers:
      - name: self-service
        image: "{{ .Values.selfservice.image }}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "0.5Gi"
        livenessProbe:
          httpGet:
            path: "/"
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: "/"
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 30                      
        imagePullPolicy: Always
        name: self-service
        ports:
        - containerPort: 80
          name: self-service
        #resources: {}
      restartPolicy: Always
#      serviceAccountName: ""
#      volumes: null
{{- end }}